# Generated by Django 3.1.3 on 2021-02-10 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombres', models.CharField(help_text='Nombres del Cliente', max_length=100)),
                ('apellidos', models.CharField(help_text='Apellidos del Cliente', max_length=100)),
                ('CiRuc', models.CharField(help_text='Cedula / Ruc o Pasaporte del Cliente', max_length=13)),
                ('esRucPasaporte', models.BooleanField(default=False)),
                ('direccion', models.CharField(help_text='Dirección del Cliente', max_length=13)),
                ('estado', models.BooleanField(default=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
