# Generated by Django 3.0.7 on 2021-02-05 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_marca_producto_subcategoria_unidadmedida'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='uc',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='SubCategoria',
        ),
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
    ]
